### ISSUE TITLE
Visibility of pool folders

### ISSUE THREAD

**Issue by mhilbert** [studer-raimann/LearnLoc#12]
When creating a learning location object a corresponding pool folder will be created, too.
The owner of the pool folder is root, although it makes more sense when the owner of the learning location object is also the owner of the pool folder.

The pool folders are invisible for all members of the course, although it would be helpful when preparing e-learning content if they are visible for course administrators and course tutors.

**Comment by chfsx** [comment]
this is due to a limitation of ILIAS. We would like to implement LearnLocs as a Container-Plugin, but currently there is no such Plugin-Slot. Therefore a folder is created, but it should be invisible for course members. You can set the right for the folder as you like
