### ISSUE TITLE
Campus Tour Option

### ISSUE THREAD

**Issue by sebastianz1980** [studer-raimann/LearnLoc#5]
Hi, 

I have installed the plugin and it works great but I have a question about the "Campus Tour" Option. In the plugin configuration I added a ref_id for a course that contains LearnLoc objects. For username and password I entered the Information from an account within the couse. 
I thought now every user logged into the app with an normal account can see the Campus Tour, but this isn't working. When I add the user logged in in the app to the course everything is fine. Did I make something wrong or isn't it the way it should work?

Next question: Is the a way to hide the new Location Button in the App to user who doesn't have the right to add a location in ilias? 

Plugin version: 2.2.00
ILIAS: 5.1.4 
Tested with iOS App

greets
Sebastian

**Comment by chfsx** [comment]
Hi Sebastian

Currently the CampuTour functionality does not affect the Apps. This Feature only works with the App of the University of Hohenheim, which has Learning Locations built in to their App. I'll mark this in the Settings-page with a label to prevent from confusing. thanks for the input.

The misleading button is a bug we will fix with the next version of the apps, thanks for the report.

Greets Fabian

**Comment by chfsx** [comment]
Button will be fixed in next release of the app (this week)
