### ISSUE TITLE
ERROR: Can't find target class illearnlocconfiggui for node 3p:87 (iladministrationgui).

### ISSUE THREAD

**Issue by colin-kiegel** [studer-raimann/LearnLoc#7]
please add a short notice in README.md to reload the **control structure** in the setup.

**Comment by chfsx** [comment]
This should be done with the installation/update of the plugin. there was a bug in ILIAS 5.1 where the ConfigGUIs were not recognized during the update, maybe this was the problem, could that be?

**Comment by colin-kiegel** [comment]
Yes, it occurred with 5.1.x, but not the newest revision.
